### ISSUE TITLE
New Flip Button and problem with duplicate HBStickerView solved

### ISSUE THREAD

**Issue by SergioMusoles** [AvtMob/HBStickerViewOrResizableView#1]
Hello, I d'ont know how this GitHub works to add new functions to open repositories, so I will tell you.
I have downloaded your HBStickerView and added a "flip" button, to rotate the image as if it were in a mirror, to change the "sense" of the image.
Also, I have seen that there was a problem that two views were created inside the HBStickerView, so the views were duplicated, and although at first the problem was not seen, when using the new flip button I have seen the problem, and also I have solved it.
Can I upload the new code to your repository?

**Comment by AvtMob** [comment]
@SergioMusoles if you are still available then I can add you as collaborator. Add a reply comment

**Comment by SergioMusoles** [comment]
Sure, of course. I would be happy to collaborate.

**Comment by AvtMob** [comment]
Great! @SergioMusoles pull the latest  code and merge your changes and create PR for that.

**Comment by SergioMusoles** [comment]
Hi, I'm new to using GitHub for shared projects. I've already downloaded the latest code and added my changes, but when I push to xCode it says "Authentication failed because the credentials were rejected". I don't know if the problem is because I'm not a collaborator and you have to add me as a collaborator to push.
Thanks and sorry to bother you but I'm learning how to use Git

**Comment by AvtMob** [comment]
@SergioMusoles 

Nobody can push directly to public repository if owner is not already granting you write access.

The process for contributing to a public repository in GitHub starts by forking the repository, then pushing the change onto the forked, then creating a pull request onto the original repository. After that comes the role of the project owner to review and take action (merge/decline) of the requested code change.

For more details, please check the below helpful article:

https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project

**Comment by SergioMusoles** [comment]
I think the work is done on my part. Thank you very much for the explanations, the patience, and the helpful article that you sent me, greetings!

**Comment by AvtMob** [comment]
@SergioMusoles if you like my work. Don't forgot to follow me on GitHub and do star for repos thanks
